### ISSUE TITLE
Wrong Dedicated Server URL

### ISSUE THREAD

**Issue by djdanby** [pchoiniere/FSModManager#1]
I always get the error message that the URL I specified is not a dedicated server URL. But it is entered correctly. Why is that?

Server is a GPortal Server.

Screenshot `https://ibb.co/HP80SG9`

**Comment by pchoiniere** [comment]
Did you update to the latest version? This fixed in version 1.1.4 on 10/26/2022. If you are still getting this issue, then send me the url you are using and I put it though the debugger and see why it is happening.

**Comment by djdanby** [comment]
Yes. I use the latest version. Does this tool need some other settings an a dedicated server? Our Modlist is open. But to open the Modlist on server, we need a Username and a Password. And in your tool i dont have a Loginname.

PS: The Modlist is useless for you without the our Login Data. U can not see the list.

**Comment by pchoiniere** [comment]
Likely you didn't turn on public mod download.  
1. Open the Dedicated Server web page
2. Click "Settings" at the top
3. Scroll to the bottom and activate the "Public Mod Download"
4. Use the "Link to active mods" url

**Comment by djdanby** [comment]
Ah ok.  I almost guessed that. Then I give up the tool. We use a lot of private mods. If we make the link public, then anyone can access it through the URL. If, for example, members leave us, we change the access data accordingly. An open download link is therefore out of the question. It would be nice if you could enter a username here. And the mods can also be downloaded behind closed pages.

**Comment by pchoiniere** [comment]
That would be a nice option. I will add that to me todo list.

**Comment by pchoiniere** [comment]
Version 1.2.0 now allows you to use a dedicated server web username and password to download mods without activating the "Public Mod Download".

**Comment by djdanby** [comment]
Same problem like before. :-/ 

[https://ibb.co/PFnCxbB](https://ibb.co/PFnCxbB)

**Comment by pchoiniere** [comment]
I notice that you desktop is not in the English language and/or the server is not.  Take your url and append to the end this "?login=true&username=user0&password=passwordForUser0Here" without the quotes.  Here's an example: 
http://45.136.224.65:8640/mods.html?login=true&username=user0&password=user0Password
Get the html that was returned and send it to me. You can do that with Chrome by right clicking and select "View page source". I look at the html for some info so I know that it is a FS22 mod page and it must be different then mine. You can strip out the mods if you want, mostly looking at the header and footer of the html

**Comment by djdanby** [comment]
Ok. Here is it. I hope that helps you :)
[https://workupload.com/file/Pq8JQffgXRT](url)

**Comment by pchoiniere** [comment]
The file you sent me is working correctly so it must be another issue. I'm adding some troubleshooting to the add/edit mod folder window to show was found and save it to a file.  Can you please install 1.2.1 and save that file and send it to me? Thanks.

**Comment by djdanby** [comment]
Here it is https://workupload.com/file/nS6ffCeBskX

**Comment by pchoiniere** [comment]
Found the problem and fixed in 1.2.2, I was not sending the user name and password during the creation of a new button, everywhere else I was doing it correctly. Not sure how it got past me. Try it and let me know.

**Comment by djdanby** [comment]
It works now. GREAT JOB. Thank you very much :)
