### ISSUE TITLE
Mod Downloads does not work correctly

### ISSUE THREAD

**Issue by djdanby** [pchoiniere/FSModManager#2]
Hello. Me again :)
I don't know if you've noticed, but currently the downloads of the mods from the server don't work properly. 
The mod manager only downloads files that are 1kb in size. It does show the correct size in the manager when downloading. But in the folder land only 1 kb large files.
I have tested this on a server that does not require login data.

Mod Manager Version: 1.2.7.107

[Screenshot](https://ibb.co/V9vVw2Z)

**Comment by pchoiniere** [comment]
Version 1.2.8, fixes this problem. Sorry for the inconvenience.

**Comment by djdanby** [comment]
Ok. So far so good. He is loading again. Thank you. :)
