### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by djdanby** [pchoiniere/FSModManager#3]
Hello :)
One Question.
Instead of right-clicking to make a profile active, could you give your mod manager little left-click buttons like this to make them active?
That would be great. Especially if you always switch back and forth between the profiles when modding. Because you usually don't always start the game immediately. Maybe because it's possible in colour, like on my example graphic.

So only if it doesn't take too much effort and you think it's good :)

[Preview](https://abload.de/img/fsmodexamplewld59.png)

**Comment by pchoiniere** [comment]
New build is out with an invisible button to the left of the mod folder button. Move your cursor there and it will appear. Click on it to make that mod folder button active.

**Comment by djdanby** [comment]
Very Nice. Thank u very much :) Ur the best :)
